#include "platform.h"
#include "emu.h"

#ifdef DEBUG
# define INSN_MAP_ENTRY(insn) [RV_INSN__##insn] = #insn
# define INSN_MAP_ENTRY_S(insn, repr) [RV_INSN__##insn] = repr
const char* const repr_insn_map[] = {
  INSN_MAP_ENTRY(INVALID),
  INSN_MAP_ENTRY(LUI),
  INSN_MAP_ENTRY(AUIPC),
  INSN_MAP_ENTRY(JAL),
  INSN_MAP_ENTRY(JALR),
  INSN_MAP_ENTRY(BEQ),
  INSN_MAP_ENTRY(BNE),
  INSN_MAP_ENTRY(BLT),
  INSN_MAP_ENTRY(BGE),
  INSN_MAP_ENTRY(BLTU),
  INSN_MAP_ENTRY(BGEU),
  INSN_MAP_ENTRY(LB),
  INSN_MAP_ENTRY(LH),
  INSN_MAP_ENTRY(LW),
  INSN_MAP_ENTRY(LBU),
  INSN_MAP_ENTRY(LHU),
  INSN_MAP_ENTRY(SB),
  INSN_MAP_ENTRY(SH),
  INSN_MAP_ENTRY(SW),
  INSN_MAP_ENTRY(ADDI),
  INSN_MAP_ENTRY(SLTI),
  INSN_MAP_ENTRY(SLTIU),
  INSN_MAP_ENTRY(XORI),
  INSN_MAP_ENTRY(ORI),
  INSN_MAP_ENTRY(ANDI),
  INSN_MAP_ENTRY(SLLI),
  INSN_MAP_ENTRY(SRLI),
  INSN_MAP_ENTRY(SRAI),
  INSN_MAP_ENTRY(ADD),
  INSN_MAP_ENTRY(SUB),
  INSN_MAP_ENTRY(SLL),
  INSN_MAP_ENTRY(SLT),
  INSN_MAP_ENTRY(SLTU),
  INSN_MAP_ENTRY(XOR),
  INSN_MAP_ENTRY(SRL),
  INSN_MAP_ENTRY(SRA),
  INSN_MAP_ENTRY(OR),
  INSN_MAP_ENTRY(AND),
  INSN_MAP_ENTRY(FENCE),
  INSN_MAP_ENTRY(FENCE_I),
  INSN_MAP_ENTRY(ECALL),
  INSN_MAP_ENTRY(EBREAK),
  INSN_MAP_ENTRY(CSRRW),
  INSN_MAP_ENTRY(CSRRS),
  INSN_MAP_ENTRY(CSRRC),
  INSN_MAP_ENTRY(CSRRWI),
  INSN_MAP_ENTRY(CSRRSI),
  INSN_MAP_ENTRY(CSRRCI),
#ifdef EXT_RV32M
  INSN_MAP_ENTRY(MUL),
  INSN_MAP_ENTRY(MULH),
  INSN_MAP_ENTRY(MULHSU),
  INSN_MAP_ENTRY(MULHU),
  INSN_MAP_ENTRY(DIV),
  INSN_MAP_ENTRY(DIVU),
  INSN_MAP_ENTRY(REM),
  INSN_MAP_ENTRY(REMU),
#endif
#ifdef EXT_RV32FD
  INSN_MAP_ENTRY_S(FLx, "fl.x"),
  INSN_MAP_ENTRY_S(FSx, "fs.x"),
  INSN_MAP_ENTRY_S(FMADDx, "fmadd.x"),
  INSN_MAP_ENTRY_S(FMSUBx, "fmsub.x"),
  INSN_MAP_ENTRY_S(FNMADDx, "fnmadd.x"),
  INSN_MAP_ENTRY_S(FNMSUBx, "fnmsub.x"),
  INSN_MAP_ENTRY_S(FADDx, "fadd.x"),
  INSN_MAP_ENTRY_S(FSUBx, "fsub.x"),
  INSN_MAP_ENTRY_S(FMULx, "fmul.x"),
  INSN_MAP_ENTRY_S(FDIVx, "fdiv.x"),
  INSN_MAP_ENTRY_S(FSQRTx, "fsqrt.x"),
  INSN_MAP_ENTRY_S(FSGNJx, "fsgnj.x"),
  INSN_MAP_ENTRY_S(FSGNJNx, "fsgnjn.x"),
  INSN_MAP_ENTRY_S(FSGNJXx, "fsgnjx.x"),
  INSN_MAP_ENTRY_S(FMINx, "fmin.x"),
  INSN_MAP_ENTRY_S(FMAXx, "fmax.x"),
  INSN_MAP_ENTRY_S(FCVT_W_x, "fcvt.w.x"),
  INSN_MAP_ENTRY_S(FCVT_WU_x, "fcvt.wu.x"),
  INSN_MAP_ENTRY_S(FCVT_x_W, "fcvt.x.w"),
  INSN_MAP_ENTRY_S(FCVT_x_WU, "fcvt.x.wu"),
  INSN_MAP_ENTRY_S(FEQx, "feq.x"),
  INSN_MAP_ENTRY_S(FLTx, "flt.x"),
  INSN_MAP_ENTRY_S(FLEx, "fle.x"),
  INSN_MAP_ENTRY_S(FCLASSx, "fclass.x"),
  INSN_MAP_ENTRY_S(FMV_W_x, "fmv.w.x")
#endif
};

const char* const repr_reg_abi_map[] = {
  "zero",
  "ra",
  "sp",
  "gp",
  "tp",
  "t0",
  "t1",
  "t2",
  "s0",
  "s1",
  "a0",
  "a1",
  "a2",
  "a3",
  "a4",
  "a5",
  "a6",
  "a7",
  "s2",
  "s3",
  "s4",
  "s5",
  "s6",
  "s7",
  "s8",
  "s9",
  "s10",
  "s11",
  "t3",
  "t4",
  "t5",
  "t6"
};
# undef INSN_MAP_ENTRY
#endif