#include "platform.h"
#include "emu.h"

#ifdef DEBUG
# define _INSN_MAP_ENTRY(insn) [RV_INSN__##insn] = #insn
const char* const repr_insn_map[] = {
  _INSN_MAP_ENTRY(LUI),
  _INSN_MAP_ENTRY(AUIPC),
  _INSN_MAP_ENTRY(JAL),
  _INSN_MAP_ENTRY(JALR),
  _INSN_MAP_ENTRY(BEQ),
  _INSN_MAP_ENTRY(BNE),
  _INSN_MAP_ENTRY(BLT),
  _INSN_MAP_ENTRY(BGE),
  _INSN_MAP_ENTRY(BLTU),
  _INSN_MAP_ENTRY(BGEU),
  _INSN_MAP_ENTRY(LB),
  _INSN_MAP_ENTRY(LH),
  _INSN_MAP_ENTRY(LW),
  _INSN_MAP_ENTRY(LBU),
  _INSN_MAP_ENTRY(LHU),
  _INSN_MAP_ENTRY(SB),
  _INSN_MAP_ENTRY(SH),
  _INSN_MAP_ENTRY(SW),
  _INSN_MAP_ENTRY(ADDI),
  _INSN_MAP_ENTRY(SLTI),
  _INSN_MAP_ENTRY(SLTIU),
  _INSN_MAP_ENTRY(XORI),
  _INSN_MAP_ENTRY(ORI),
  _INSN_MAP_ENTRY(ANDI),
  _INSN_MAP_ENTRY(SLLI),
  _INSN_MAP_ENTRY(SRLI),
  _INSN_MAP_ENTRY(SRAI),
  _INSN_MAP_ENTRY(ADD),
  _INSN_MAP_ENTRY(SUB),
  _INSN_MAP_ENTRY(SLL),
  _INSN_MAP_ENTRY(SLT),
  _INSN_MAP_ENTRY(SLTU),
  _INSN_MAP_ENTRY(XOR),
  _INSN_MAP_ENTRY(SRL),
  _INSN_MAP_ENTRY(SRA),
  _INSN_MAP_ENTRY(OR),
  _INSN_MAP_ENTRY(AND),
  _INSN_MAP_ENTRY(FENCE),
  _INSN_MAP_ENTRY(FENCE_I),
  _INSN_MAP_ENTRY(ECALL),
  _INSN_MAP_ENTRY(EBREAK),
  _INSN_MAP_ENTRY(CSRRW),
  _INSN_MAP_ENTRY(CSRRS),
  _INSN_MAP_ENTRY(CSRRC),
  _INSN_MAP_ENTRY(CSRRWI),
  _INSN_MAP_ENTRY(CSRRSI),
  _INSN_MAP_ENTRY(CSRRCI)
};

const char* const repr_reg_abi_map[] = {
  "zero",
  "ra",
  "sp",
  "gp",
  "tp",
  "t0",
  "t1",
  "t2",
  "s0",
  "s1",
  "a0",
  "a1",
  "a2",
  "a3",
  "a4",
  "a5",
  "a6",
  "a7",
  "s2",
  "s3",
  "s4",
  "s5",
  "s6",
  "s7",
  "s8",
  "s9",
  "s10",
  "s11",
  "t3",
  "t4",
  "t5",
  "t6"
};
# undef _INSN_MAP_ENTRY
#endif